# Generated by Django 4.2 on 2024-05-24 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_inmueble_fecha_creacion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contactos',
            new_name='Mensajes',
        ),
    ]
