# Generated by Django 4.2 on 2024-05-27 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_mensajes_estado_respuestas'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionComuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50)),
                ('comuna', models.CharField(max_length=50)),
            ],
        ),
    ]
