# Generated by Django 4.2 on 2024-05-28 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_rename_comuna_regioncomuna_comunas'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='inmuebles'),
        ),
    ]
