# Generated by Django 4.2 on 2024-05-31 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_inmueble_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='visitas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
