# Generated by Django 4.2 on 2024-06-01 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_inmueble_visitas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='visitas',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
